#! /bin/sh

xrandr --output DisplayPort-0 --mode 1920x1080 --rate 144.00 --primary

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
#bspc monitor -d 01 02 03 04 05 06 07 08 09 00 '--' '==' '<=' IS HO 'P^' DL ED 'Pv' 00 01 02 03 04 05 06 07 08 09 '//' '**' -- ++ RT DL
#bspc monitor -d '~' 1 2 3 4 5 6 7 8 9 0 '-' '=' '<-' I H '^' D E 'v' 0 1 2 3 4 5 6 7 8 9 '/' '*' - + R d
bspc monitor -d '~' 1 2 3 4 5 6 7 8 9 0 '-' '=' '<-' I H '^' D E 'v' 0 1 2 3 4 5 6 7 8 9 '/' '*' - + d

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false # da ne se dviji (centrira?) mishkata kato smenqm desktopa
bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a firefox desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Yad state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a discord desktop='^1'


#
# Floating Windows
#
# tlauncher
bspc rule -a ru-turikhay-tlauncher-bootstrap-Bootstrap state=floating
# gnome calculator
bspc rule -a Gnome-calculator state=floating
# calendara
bspc rule -a Io.elementary.calendar state=floating


# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"


#
# Autostart
#

# Thunar caching so that it doesn't take 99 years to start
thunar --daemon &

# Taskbar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# Wallpaper
nitrogen --restore &

# Autostart
#dex -a -s /etc/xdg/autostart/:~/.config/autostart/  

# Compositor
#picom -CGb &

# Network Applet
nm-applet --indicator &

# Klaviaturata ezici
fcitx5 &

# Mate specific
#/usr/lib/mate-settings-daemon/mate-settings-daemon &

# Cursor
xsetroot -cursor_name left_ptr &
