#! /bin/sh

xrandr --output DisplayPort-0 --mode 1920x1080 --rate 144.00 --primary

pgrep -x sxhkd > /dev/null || sxhkd &

if [ "$(xrandr --current | grep eDP1)" -ne "" ] ;then
	xrandr --output eDP1 --gamma 1.0:1.0:0.8
fi

#bspc monitor -d 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
#bspc monitor -d 01 02 03 04 05 06 07 08 09 00 '--' '==' '<=' IS HO 'P^' DL ED 'Pv' 00 01 02 03 04 05 06 07 08 09 '//' '**' -- ++ RT DL
#bspc monitor -d '~' 1 2 3 4 5 6 7 8 9 0 '-' '=' '<-' I H '^' D E 'v' 0 1 2 3 4 5 6 7 8 9 '/' '*' - + R d
bspc monitor -d '~' 1 2 3 4 5 6 7 8 9 0 '-' '=' '<-' I H '^' D E 'v' 0 1 2 3 4 5 6 7 8 9 '/' '*' - + d

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false # da ne se dviji (centrira?) mishkata kato smenqm desktopa
bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a firefox desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Yad state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a discord desktop='^1'


#
# Floating Windows
#
# tlauncher
bspc rule -a ru-turikhay-tlauncher-bootstrap-Bootstrap state=floating
# gnome calculator
bspc rule -a Gnome-calculator state=floating
# calendara
bspc rule -a Io.elementary.calendar state=floating


# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"


#
# Autostart
#

# Thunar caching so that it doesn't take 99 years to start
#thunar --daemon &

# Taskbar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# Wallpaper
nitrogen --restore &

# Autostart
#dex -a -s /etc/xdg/autostart/:~/.config/autostart/

# Compositor
#picom -CGb &

# Network Applet
nm-applet --indicator &

# Klaviaturata ezici
#fcitx5 &

# Mate specific
#/usr/lib/mate-settings-daemon/mate-settings-daemon &

# Cursor
xsetroot -cursor_name left_ptr &

# Audio sharing
sleep 10
# create sinks and virtual mic
pactl load-module module-null-sink media.class=Audio/Sink sink_name=audio-sharing-sink channel_map=stereo
pactl load-module module-null-sink media.class=Audio/Sink sink_name=IGNORE-ME-reduced-volume-sink channel_map=stereo
pactl load-module module-null-sink media.class=Audio/Source/Virtual sink_name=my-virtualmic channel_map=front-left,front-right
# redirect real mic to virtual mic
pw-link alsa_input.usb-C-Media_Electronics_Inc._Redragon_Gaming_Headset-00.mono-fallback:capture_MONO my-virtualmic:input_FL
# redirect regular sink to lower volume sink
pw-link audio-sharing-sink:monitor_FL IGNORE-ME-reduced-volume-sink:playback_FL
pw-link audio-sharing-sink:monitor_FR IGNORE-ME-reduced-volume-sink:playback_FR
# redirect lower volume sink to virtual mic
pw-link IGNORE-ME-reduced-volume-sink:monitor_FL my-virtualmic:input_FL
pw-link IGNORE-ME-reduced-volume-sink:monitor_FR my-virtualmic:input_FR
# set volume on lower volume sink
pactl set-sink-volume IGNORE-ME-reduced-volume-sink 50%
# connect regular sink to headphones
pw-link audio-sharing-sink:monitor_FL alsa_output.usb-C-Media_Electronics_Inc._Redragon_Gaming_Headset-00.analog-stereo:playback_FL
pw-link audio-sharing-sink:monitor_FR alsa_output.usb-C-Media_Electronics_Inc._Redragon_Gaming_Headset-00.analog-stereo:playback_FR
